import day_11


class TestDay11:


    def test_example_part1_values(self):
        distances = day_11.shortest_distances((l for l in ('''...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....'''.split('\n'))))
        assert (1, 7, 15) in distances
        assert (3, 6, 17) in distances
        assert (8, 9, 5) in distances

    def test_example_part1_sum(self):
        assert day_11.sum_shortest_distances((l for l in ('''...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....'''.split('\n')))) == 374

    def test_example_part1_sum_10(self):
        assert day_11.sum_shortest_distances((l for l in ('''...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....'''.split('\n'))), expansion=10) == 1030

    def test_example_part1_sum_100(self):
        assert day_11.sum_shortest_distances((l for l in ('''...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....'''.split('\n'))), expansion=100) == 8410


